export interface AdminModule {
  id: string;
  name: string;
  description: string;
  icon: string;
  route: string;
  permissionRequired: string;
  hasWidget: boolean;
  widgetComponent?: string;
  isCore: boolean;
  version: string;
}

export const ADMIN_MODULE_REGISTRY: AdminModule[] = [
  {
    id: 'dashboard',
    name: 'Dashboard Overview',
    description: 'Executive analytics, real-time sales metrics, and logistics health',
    icon: 'LayoutDashboard',
    route: '/admin',
    permissionRequired: 'dashboard.view',
    hasWidget: true,
    widgetComponent: 'DashboardStatsWidget',
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'products',
    name: 'Products & Catalog',
    description: 'Bilingual catalog, variants, dynamic attributes and multi-type items',
    icon: 'Package',
    route: '/admin/products',
    permissionRequired: 'products.view',
    hasWidget: true,
    widgetComponent: 'LowStockAlertWidget',
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'inventory',
    name: 'Warehouses & Stock',
    description: 'Multi-warehouse stock levels, reservations, adjustments and low-stock alerts',
    icon: 'Building',
    route: '/admin/inventory',
    permissionRequired: 'inventory.manage',
    hasWidget: true,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'orders',
    name: 'Orders & Invoices',
    description: 'Order processing, bilingual printable invoices, status updates, and tracking',
    icon: 'ShoppingBag',
    route: '/admin/orders',
    permissionRequired: 'orders.view',
    hasWidget: true,
    widgetComponent: 'RecentOrdersWidget',
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'couriers',
    name: 'Couriers & Dispatch',
    description: 'Steadfast & Pathao Courier API integration, tracking, and settlements',
    icon: 'Truck',
    route: '/admin/couriers',
    permissionRequired: 'shipping.manage',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'payments',
    name: 'Payment Gateways',
    description: 'Manage bKash, Nagad, SSLCommerz, Stripe, COD and General Ledger linkage',
    icon: 'CreditCard',
    route: '/admin/payments',
    permissionRequired: 'gateways.manage',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'accounting',
    name: 'General Ledger & ERP',
    description: 'Double-entry chart of accounts, journal entries, balance sheet, and revenue',
    icon: 'BookOpen',
    route: '/admin/accounting',
    permissionRequired: 'accounting.view',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'crm',
    name: 'CRM & Support',
    description: 'Customer profiles, support tickets, loyalty points ledger, and promo coupons',
    icon: 'Users',
    route: '/admin/crm',
    permissionRequired: 'customers.view',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'subscriptions',
    name: 'License Keys & Passes',
    description: 'Encrypted software license pools & third-party subscription access passes',
    icon: 'Key',
    route: '/admin/subscriptions',
    permissionRequired: 'products.manage',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'policies',
    name: 'Legal & Consent Audit',
    description: 'Policy versioning (Terms, Privacy, Return, Refund) and customer consent logs',
    icon: 'FileCheck',
    route: '/admin/policies',
    permissionRequired: 'legal.manage',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'currencies',
    name: 'Multi-Currency & FX',
    description: 'Manage 10 regional currencies, decimal precision and exchange rates',
    icon: 'DollarSign',
    route: '/admin/currencies',
    permissionRequired: 'currencies.manage',
    hasWidget: true,
    widgetComponent: 'CurrencyBreakdownWidget',
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'translations',
    name: 'Content & Translations',
    description: 'Live editor for English and natural Bengali storefront copy & policies',
    icon: 'Languages',
    route: '/admin/translations',
    permissionRequired: 'translations.manage',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'operations',
    name: 'Warehouse Operations',
    description: 'Barcode scanning, order picking, packing, manifests, and serialized inventory',
    icon: 'Scan',
    route: '/admin/operations',
    permissionRequired: 'inventory.manage',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
  {
    id: 'settings',
    name: 'Store Settings Hub',
    description: 'Centralized store identity, shipping rates, SEO metadata, and brand theme',
    icon: 'Settings',
    route: '/admin/settings',
    permissionRequired: 'settings.manage',
    hasWidget: false,
    isCore: true,
    version: '1.0.0',
  },
];
